### ISSUE TITLE
Speculative leftHeader styling to rightHeader

### ISSUE THREAD

**Issue by alsoGAMER** [stpnwf/ZestyTheme#30]
**Describe your idea**
I tried implementing the same styling for the leftHeader component and I'm testing it on my server for quite a while now, but I can't manage to get the Header to expand based on the title of the currently playing media (in the player).

Can someone guide me into having that working?

**Screenshots**
Current result of leftHeader component in homescreen
![Image](https://github.com/user-attachments/assets/89443936-97fb-447b-890b-99863a8870f3)

Current result of leftHeader component in the player (as you can see, the media title is only shown partially)
![Image](https://github.com/user-attachments/assets/364a3601-4ccd-45b9-baba-e6671bd2483a)

<details>
<summary>Custom CSS I added/modified to achieve this</summary>

```css
  /* Rounded header buttons */

  .headerTabs, .headerRight, .headerLeft {
      background-color:rgba(var(--white-off), 0.35) !important;
      border-radius: var(--rounding-circle) !important;
      color: rgba(var(--darkest)) !important;
      backdrop-filter: blur(50px) !important;
  }

.headerRight {
  margin-left: auto; 
margin-right: 0;
}

.headerLeft {
    width: 237px;
      max-width: 237px;
text-shadow: none !important;
}

  .layout-desktop .layout-mobile .headerTabs, .layout-desktop .headerRight .headerLeft {
   box-shadow: 1px 3px 6px rgba(var(--darkest),.5);
  }

.layout-desktop .layout-mobile .headerRight .headerLeft {
    box-shadow: 1px 3px 6px rgba(var(--darkest), .5);
}

  /* Removes hover bg from left headerbar */

  .headerLeft .paper-icon-button-light:hover, .headerLeft .paper-icon-button-light:hover:not(:disabled) {
    background-color: transparent !important;
  }

  .headerLeft .paper-icon-button-light:focus, .headerLeft .paper-icon-button-light:focus:not(:disabled) {
    background-color: transparent !important;
  }

  /* Button height */
  .headerRight,
.headerLeft,
  .layout-desktop .emby-tab-button {
      height: 45px !important;
  }
```
</details>
