### ISSUE TITLE
Added profile picture of actors, the poster of movies, tv shows, season and episodes

### ISSUE THREAD

**Issue by J0nan** [stpnwf/ZestyTheme#5]
I have forked your repo and made some modifications. Also made some tweaks so anyone can chose how to customize their Jellyfin. Feel free to take a look and copy anything (https://github.com/J0nan/ZestyTheme).

I have added the profile picture of actors, the poster of movies, tv shows, season and episodes. If have not tested very much, but it kind of works. I small screens it will not show.
I am not making you a PR because I have made many other changes as somethings I wanted them done in other ways. 

Here is the lines of code in my fork
https://github.com/J0nan/ZestyTheme/blob/8ef98457105ab378498d40c63b53a340471d4d29/theme.css#L74 

And here the code:

```css
.layout-desktop .detailImageContainer .card {
  position: absolute !important;
  top: -16vh;
  left: 65vw;
  /* max-height: 60vh; */
  padding-right: 4vw;
  width: 20em;
}

@media (max-width: 68.75em) {
  .layout-desktop .detailImageContainer .card {
      display: none;
  }
}
```

With this, I had to modify the Next episode, because in some cases they overlap.
Here it is in my fork:
https://github.com/J0nan/ZestyTheme/blob/8ef98457105ab378498d40c63b53a340471d4d29/theme.css#L2113

And here the code:

```css
/* Moves TV shows Up Next to bottom right */
.layout-desktop .nextUpSection {
	border-radius: 34px;
	left: calc(70vw - 0.5em);
	margin-right: -30vw;
	margin-top: 25vh;
	margin-bottom: 1vh;
	padding-left: 2.5em;
	margin-right: 5vw;
	background-color: rgba(var(--darkest),.8);
	padding-top: .3em;
	backdrop-filter: blur(4px);
	position: absolute;
}
```

Feel free to close this issue as soon as you read this, or whenever you feel like it.

Thanks for the work!
